configure.ac: Turn deprecated-declarations errors into warnings
Like:
../../git/lib/dvb_ci/dvbci_ccmgr.cpp:905:24: error: 'void AES_cbc_encrypt(const unsigned char*, unsigned char*, size_t, const AES_KEY*,
unsigned char*, int)' is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
|   905 |         AES_cbc_encrypt(src, dst, len, &key, iv, encrypt);
|       |         ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Low level APIs OpenSSL are marked as deprecated.